name: aristys_app
description: Aristys app

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.6
  flutter_staggered_grid_view: "^0.2.3"
  cupertino_icons: ^0.1.0
  shrine_images: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Regular.ttf
        - asset: fonts/Rubik-Medium.ttf
          weight: 500

  uses-material-design: true
  assets:
    - assets/aristys.png
