name: aristys_app
description: Aristys app

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.6
  flutter_staggered_grid_view: "^0.2.3"
  cupertino_icons: ^0.1.0
  json_annotation: ^2.0.0
  path_provider: ^0.4.1
  rxdart: 0.16.7
  sqflite: ^0.12.2+1
  redux: ^3.0.0
  flutter_redux: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

flutter:
  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Regular.ttf
        - asset: fonts/Rubik-Medium.ttf
          weight: 500

  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/agence.png
    - assets/expertises.png
    - assets/clients.png
    - assets/blog.png
    - assets/contact.png
